import type { Metadata } from 'next'
import './globals.css'
import { Alata, Josefin_Sans } from 'next/font/google'
import Navigation from '../components/Navigation'

const alata = Alata({
  weight: '400',
  variable: '--font-alata',
  subsets: ['latin'],
})

const josefinSans = Josefin_Sans({
  variable: '--font-josefin-sans',
  subsets: ['latin'],
  weight: '300',
})

export const metadata: Metadata = {
  title: 'Loopstudios landing page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${alata.variable} ${josefinSans.variable} h-full bg-black antialiased`}
    >
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
